### ISSUE TITLE
Exception thrown when deleting a micropost

### ISSUE THREAD

**Issue by cdelmoral** [cdelmoral/angularjs-tutorial#14]
DELETE /api/users/56c7f31560ee40e40a3fd1b7/microposts/583d195729b8a4060722926b - - ms - -
Warning: a promise was created in a handler but was not returned from it
    at Query.<anonymous> (/Users/carlos/Projects/angularjs-tutorial/node_modules/mongoose/lib/model.js:3324:16)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/kareem/index.js:259:21
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/kareem/index.js:127:16
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
From previous event:
    at model.wrappedPointCut [as remove] (/Users/carlos/Projects/angularjs-tutorial/node_modules/mongoose/lib/document.js:1890:21)
    at MicropostsController.destroy (/Users/carlos/Projects/angularjs-tutorial/dist/microposts/microposts-controller.js:24:17)
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/route.js:131:13)
    at /Users/carlos/Projects/angularjs-tutorial/dist/sessions/sessions-helper.js:16:7
    at Function.SessionHelper.loggedIn (/Users/carlos/Projects/angularjs-tutorial/dist/sessions/sessions-helper.js:7:5)
    at SessionHelper.correctUser (/Users/carlos/Projects/angularjs-tutorial/dist/sessions/sessions-helper.js:14:17)
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:277:22
    at param (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:349:14)
    at paramCallback (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:401:21)
    at /Users/carlos/Projects/angularjs-tutorial/dist/microposts/microposts-controller.js:9:5
From previous event:
    at MicropostsController.find (/Users/carlos/Projects/angularjs-tutorial/dist/microposts/microposts-controller.js:7:31)
    at paramCallback (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:404:7)
    at param (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:384:5)
    at paramCallback (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:401:21)
    at /Users/carlos/Projects/angularjs-tutorial/dist/users/users-controller.js:12:5
From previous event:
    at UsersController.find (/Users/carlos/Projects/angularjs-tutorial/dist/users/users-controller.js:10:26)
    at paramCallback (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:404:7)
    at param (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:384:5)
    at Function.process_params (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:271:10)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/route.js:121:14)
    at /Users/carlos/Projects/angularjs-tutorial/dist/sessions/sessions-controller.js:16:5
    at Query.<anonymous> (/Users/carlos/Projects/angularjs-tutorial/node_modules/mongoose/lib/model.js:3324:16)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/kareem/index.js:259:21
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/kareem/index.js:127:16
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
From previous event:
    at SessionsController.find (/Users/carlos/Projects/angularjs-tutorial/dist/sessions/sessions-controller.js:11:43)
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:277:22
    at param (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:312:13)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:271:10)
    at cors (/Users/carlos/Projects/angularjs-tutorial/node_modules/cors/lib/index.js:178:7)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/cors/lib/index.js:228:17
    at originCallback (/Users/carlos/Projects/angularjs-tutorial/node_modules/cors/lib/index.js:217:15)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/cors/lib/index.js:222:13
    at optionsCallback (/Users/carlos/Projects/angularjs-tutorial/node_modules/cors/lib/index.js:203:9)
    at /Users/carlos/Projects/angularjs-tutorial/node_modules/cors/lib/index.js:208:7
    at Layer.handle [as handle_request] (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/carlos/Projects/angularjs-tutorial/node_modules/express/lib/router/index.js:312:13)

**Comment by cdelmoral** [comment]
It is actually just a warning.
